language: python

python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"
- "3.7"
- "3.8"
- "3.9"

# install dependencies
install:
- pip install boto3==1.9.170

# run tests
script:
- python -m unittest paper_cup.test
